name: practica actions

on:
  push:
    branches:
      - main

jobs:
  practicaActions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Limpiar caché y reinstalar dependencias
        run: |
          rm -rf node_modules package-lock.json
          npm install
      - name: Build
        run: npm run lint